services:
  nats:
    image: nats:2.9.20-alpine
    container_name: nats-server
    ports:
      - "4222:4222" # nats client port
      - "8222:8222" # nats monitoring port 
    command: -DV -js
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./api-gateway:/app
    environment:
      - PRODUCTS_SERVICE_URL=http://products-service:8001
    depends_on:
      - products-service
    networks:
      - microservices-net
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  products:
    build: ./products-service
    container_name: products-service
    ports:
      - "8001:8001"
    volumes:
      - ./products-service:/app
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - microservices-net
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  orders:
    build: ./orders-service
    container_name: orders-service
    ports:
      - "8002:8002"
    volumes:
      - ./orders-service:/app
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - microservices-net
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload

  networks:
    microservices-net:
      driver: bridge



