services:
  nats:
    image: nats:2.9.20-alpine
    container_name: nats-server
    ports:
      - "4222:4222" # nats client port
      - "8222:8222" # nats monitoring port 
    command: -DV -js
    networks:
      - microservices-net

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./api-gateway:/app
    environment:
      - PRODUCTS_SERVICE_URL=http://products:8001
    depends_on:
      - products
    networks:
      - microservices-net
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  products:
    build: 
      context: ./products
      dockerfile: Dockerfile
    container_name: products
    volumes:
      - ./products:/app
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - microservices-net

  orders:
    build: 
      context: ./orders
      dockerfile: Dockerfile
    container_name: orders
    volumes:
      - ./orders:/app
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge



